name = eco2-qui-sommes-nous
description = le layout de la page "Qui sommes nous" du site eco2ticket.fr
template = eco2-qui-sommes-nous

; ========================================
; Regions
; ========================================
regions[header] = Header
regions[user_connexions] = Formulaire de connexion
regions[navigation] = Menu principal
regions[slider] = slider d'accueil
regions[formulaires] = Zones de saisie des formulaires
regions[content] = Content
regions[logo_notre histoire] = Logo de la page notre histoire
regions[logo_utilisation] = Logo utilisation du bon d'achat
regions[utilisation_en_magasin] = Comment utiliser le bon d'achat en magasin
regions[utilisation_en_covoiturage] = Comment utiliser le bon d'achat dans le co-voiturage
regions[footer] = Footer
regions[footer_empty] = Footer empty zone
regions[footer_a_propos] = A propos 
regions[informations] = Informations
regions[utilisation] = Utilisation
regions[suivez_nous] = Suivez-nous
regions[contactez_nous] = Contactez-nous
regions[copyright] = Copyright

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/qui-sommes-nous/qui-sommes-nous.layout.css

