name = Home
description = The homepage layout
template = home-layout

; ========================================
; Regions
; ========================================
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[content] = Content
regions[footer] = Footer

; ========================================
; Stylesheets
; ========================================
stylesheets[all][] = css/layouts/home/home.layout.css

; ========================================
; Previews
; ========================================
preview = preview.png
